name: amlelshefaa
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  bloc: ^8.1.0
  cached_network_image: ^3.2.3
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.1.0
  conditional_builder_null_safety: ^0.0.6
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  dots_indicator: ^2.1.0
  firebase_auth: ^4.1.4
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/pictures/
    - assets/pictures/background/
    - assets/pictures/app_icons/
    - assets/pictures/dmoor/
    - assets/pictures/on_boarding/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
